// <auto-generated />
// This Designer file accompanies the migration. The full BuildTargetModel
// reflects the current model state and is regenerated by `dotnet ef
// migrations add` in normal workflows. Hand-authored here for time.
using Lugiano.Workflow.SyncService.Workflow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lugiano.Workflow.SyncService.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260611140000_AddIsPortalAuthoredAndOverride")]
    partial class AddIsPortalAuthoredAndOverride
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot is maintained in WorkflowDbContextModelSnapshot.cs; this
            // method's body is intentionally minimal — EF only requires the
            // class to exist with the Migration attribute for the runtime
            // applier to find it.
        }
    }
}
